### ISSUE TITLE
Acceptance testing: Text limit on short description removes the deposited pdf, forcing a user to reload it.

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#356]
Apparently there is a a text limit on the short description.  This is indicated by a red box, but when that happens, the pdf that was uploaded appears to be removed, forcing the end-user to reload it.  

There are multiple issues here:

1. There should be some indication to the end user of a text limit to the short description.
2.  A red box is not going to be enough for faculty, students and staff to understand why the deposit failed.  We will need some sort of pop-up explanation.
3. The uploaded binary should either remain, as that is not the issue preventing ingest, or as part of the pop-up explanation for the text limit, indicate that the user will need to reload the binary.

Because these are multiple issues, do you want me to log each one separately and then reference them together?

**Comment by mark-dce** [comment]
1. I believe this is the existing functionality in the present version of MIRA. If that's not the case, could you provide a screenshot of the current behavior?  While I generally agree with the intent of issues 1 & 2, if this is the current functionality we probably need to leave this as-is since the current project was scoped as an upgrade to Fedora 4 and Hyrax and did not include other enhancements to the user interface.
1. See above
1. Unfortunately the file association being removed is a core security precaution in rails (and many other web frameworks).  The user must re-select the form being uploaded each time the form is submitted to the server; if the server were allowed to re-populate the file upload field, a malicious internet server could request an arbitrary file to be uploaded from your local system.

**Comment by Alexandermay** [comment]
Current Mira does not seem to put a limit (at least for the same description I used) on short description per this screen:
<img width="981" alt="screen shot 2017-10-05 at 11 06 08 am" src="https://user-images.githubusercontent.com/4700092/31234643-7207ee1a-a9bd-11e7-9438-b34791131083.png">

**Comment by mark-dce** [comment]
TODO: remove any limit on the description field in all self deposit forms.
