### ISSUE TITLE
If I add a second admin set, deposited works go into it by default.

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/epigaea#365]
1. On Dashboard, create a new admin set
2. Go to Works -> Add new work -> Relationships

The default admin set is now the new set instead of 'Default Admin Set'

**Comment by mark-dce** [comment]
@bess - I'm seeing the same behavior in my local development environment.  Is this expected behavior - that the most recently created admin set becomes the default selected in the relations tab of the create new work form?  Do you know if there's a place in the UI or console to set the default if there are multiple admin sets created, or should we give a shout out to samvera-tech to see if anyone has ideas?

**Comment by bess** [comment]
This is the way Hyrax works right now, unfortunately. However, I spoke to the community and people agree it's not ideal and agreed the behavior should be changed. I opened a ticket in the Hyrax project with a proposed fix (https://github.com/samvera/hyrax/issues/1773) and it looks like it might make it into the 2.0 release.

**Comment by mark-dce** [comment]
@mkorcy - let us know if this is an acceptable disposition of this ticket for now.  If there's a more specific resolution you'd like to see, feel free to re-open the ticket and add more detail.
