### ISSUE TITLE
WORKFLOW: Date sorting on notifications does not sort properly

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#399]
This is a known issue in Hyrax. Should be fixed in a future release:

https://github.com/samvera/hyrax/issues/1653

**Comment by mark-dce** [comment]
DCE has proposed a fix in Hyrax 2.1.0 for the date sorting problems referenced in ticket #884.  The fix is represented in the following PR: https://github.com/samvera/hyrax/pull/2741.  We expect that upstream fix to be merged as part of the Hyrax 2.1.0 release process sometime in the relatively near future.

This provides us with three options for fixing the problem as it exists in epigaea (MIRA 4.0):
1. Tufts can wait for the public release of Hyrax 2.1.0 and upgrade to the new gem at that time. PRO: least amount of work all-around, CON: there may be other functionality in that release that Tufts does not want to incorporate into MIRA, longest delay to a fix
2. Once the fix is accepted into Hyrax 2.1.0, DCE can propose a backport to Hyrax 2.0.1 which epigaea currently depends on.  We would then propose a patch release of Hyrax 2.0.2 and update the dependency in epigaea to that.  PRO: least risk fix path for Tufts.  CON: requires Hyrax committer approval, which we feel would be uncontroversial, but could be blocked for unforeseen reasons, short wait for a fix
3. Incorporate the fix directly into the epigaea codebase by overwriting the four impacted views.  PRO: can be implemented immediately.  CON: increases complexity of incorporating future releases and upgrades.

We recommend option No. 2 unless implementing a fix seems particularly urgent (then option 3) or if Tufts is planning on upgrading to 2.1 in the next few months anyway (then option 1)

**Comment by mark-dce** [comment]
Blocked by https://github.com/samvera/hyrax/pull/2765
Backport of fix https://github.com/samvera/hyrax/pull/2754

**Comment by mark-dce** [comment]
Closing - Option No. 2 (in Hyrax 2.0.2) should be available immanently and Option No.1 (in Hyrax 2.1.0) in the coming weeks (Late March / early April delivery goal)
