### ISSUE TITLE
Sari missing edit draft/revert draft buttons?

### ISSUE THREAD

**Issue by sarimauro** [curationexperts/epigaea#490]

**Comment by sarimauro** [comment]
Upon testing templates and editing metadata it appears that I do not have the save draft or revert draft buttons in the upper right of the edit metadata screen. I don't know if I have different permissions, or if I'm in the wrong screen (I was in edit of "My Favorite Novel" uploaded by Dan S.)

![SariCantSeeEditRevertDraft.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee255dda7cff0014940ba8/125516c66e82c728ace21e0d46db95882aa182a79bdaba468159f9801b4331763b1087397183f76af3006b1300051bff054a5556f9f0887ea6e7387689090be980385f76c73512febd871deb13a632c91edbe2e3d7158abd7f37ed998e47341f001881f85a3ca69f4fce5ef659ac.PNG)

**Comment by little9** [comment]
We changed this so that if a work in unpublished, the draft controls aren't present (in previous version of MIRA you couldn't make a draft of an unpublished work). If the work is published they should appear. You can publish the work by clicking 'Publish' on the show view for the work. 

Please let me know if you run into any issues with this.

**Comment by sarimauro** [comment]
Ah, yes -- thank you! All set
