### ISSUE TITLE
COLLECTIONS: I should be able to add an imported object to a collection

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#511]

**Comment by little9** [comment]
@mark-dce this is working and I think the only reason this ticket is around is because of earlier errors that were occurring with collections on the demo server that are no longer there. 

Steps to QA: 

- Create a collection
- Click on 'Import Objects'
- Select `mira_xml.xml` from fixtures
- Add the 3 pdf files from the XML to the import
- After import go to the works page in the dashboard
- Click 'Add to Collection' 
- The object is now in the collection
