### ISSUE TITLE
DATA MODEL: foaf:based_near -- what, where, how, and why?

### ISSUE THREAD

**Issue by sarimauro** [curationexperts/epigaea#545]
In <tufts:id>j9602060k</tufts:id> ("Sample with content for all fields") there is  <foaf:based_near uri="http://sws.geonames.org/187246/">http://sws.geonames.org/187246/</foaf:based_near>

What field is that pulling from? How is that data being generated (automatically? User-input?)? If it's automatically being generated, from where is it being pulled and under what circumstances (I have yet to see it in other metadata downloads)? What purpose does it serve?

**Comment by mark-dce** [comment]
This was an artifact of vanilla Hyrax behavior which links the `Spatial` field to the GeoNames controlled vocabulary service.  There was an error in rendering that caused the URL rather than the label to be shown. 

Going forward, we've removed this functionality and left the field as a plain string since we were unsure how many of the exiting values for this field in current content would resolve correctly.
