### ISSUE TITLE
COLLECTIONS: Show page doesn't show the works

### ISSUE THREAD

**Issue by val99erie** [curationexperts/epigaea#685]
When I add some works to a collection and then view that collection's show page, I can see the correct number of works that are in the collection, but no works are displayed, and there is a message stating that the collection is empty.  See attached screenshot.

EXPECTED BEHAVIOR:
If there are 3 works in the collection, I should see info about the 3 works on the collection show page.

ACTUAL BEHAVIOR:
There is a message that says the collection is empty or I don't have permission to view the works.

SCREENSHOT:

<img width="838" alt="collection_show_page" src="https://user-images.githubusercontent.com/298865/33740900-fdfa9b26-db67-11e7-8825-ef54efb01fd7.png">

**Comment by little9** [comment]
@val99erie @mark-dce I was able to reproduce this and it is happening if the works are unpublished. If the the works are published they appear in the collections UI. 

![screenshot-2017-12-13 testing collection mira](https://user-images.githubusercontent.com/4324761/33945787-fd994b0c-dfed-11e7-9808-bcae01f25b15.png)

So the actual issue is:

Unpublished works can be added to collections, but don't appear in the collections management UI until they are published.

**Comment by val99erie** [comment]
Ah that makes sense.  It's a little weird to me that an admin user would be prevented from seeing members of a collection, but this is probably the intended behavior.  We'll have to leave it up to @mark-dce to decide.

**Comment by mark-dce** [comment]
If that's the behavior in Hyrax - let's call it out as such and let Tufts know that it would have to be handled at the Hyrax level.

**Comment by mark-dce** [comment]
@mkorcy - When you're looking at the collection page, Hyrax only shows the published members of the collection, so it may look like your collection is empty even when you've assigned works to it.  If you look at the individual works, they will show all the collections they belong to as expected.

This is known behavior in Hyrax (by design, but I'm not a fan of it).  We can leave the behavior as-is as long as Tufts folks understand this is going to happen.  Alternately, we can override the page locally in the application and make all works show up regardless of their publication status, but this leaves Tufts with additional (not too much - see https://github.com/curationexperts/epigaea/pull/757/files) that Tufts has to maintain.

Can you let me know which option we should pursue, I'd lean towards option 1 even though we have the work for option 2 already done - I just wasn't sure if folks on the Tufts team would feel strongly one way or another :

- [ ] OPTION 1: Leave the collection page as-is with the knowledge that works will have to be published for them to appear here.  (PRO: no extra code to maintain; CON: unpublished collection members don't show up in view)

OR

- [ ] OPTION 2: Add the code necessary to display both published and unpublished members of collections. (PRO: shows all collection members; CON: a little extra code to maintain)

**Comment by mkorcy** [comment]
@mark-dce  We'll go with option two and maintain the code.  The feature as-is is something we'd definitely want/expect in TDL but from an administrative perspective I think people feel more comfortable with seeing the records regardless of publication status.

**Comment by mark-dce** [comment]
Still seeing this issue during 12-21 demo

**Comment by little9** [comment]
@mark-dce this wasn't deployed during the demo
