### ISSUE TITLE
WORKFLOW: Email notifications not being received

### ISSUE THREAD

**Issue by sarimauro** [curationexperts/epigaea#698]
Test case: Margaret Peachy's comment on Sari's deposit of "lead poisoning in antiquity" did not generate a notification email that was received. 

I checked my trash, spam filter, and other folders.

**Comment by bess** [comment]
I believe that some users are not receiving notifications because the email address that was verified by Amazon and the email address in use in MIRA do not match exactly. This is the case for both Margaret and Sari. Amazon verified `Margaret.Peachy@tufts.edu`,  but the address in use in the system was `margaret.peachy@tufts.edu`. I sent Margaret and Peachy new email verification requests from Amazon, to the email address that exactly matches the one in the system.

I think the problem must be with the delivery and email address verification, because delivery does work for me. I was able to comment on the lead poisoning in antiquity work and get an email:

You have a new message: Comment about Lead poisoning in antiquity

You have received a new message:

Sadler, Elizabeth O. (bess@curationexperts.com) has made a comment: 

Test comment 

Regarding title: 

Lead poisoning in antiquity (3f462543d)

Visit http://epigaea.curationexperts.com/ and go to your inbox for more info.

**Comment by sarimauro** [comment]
I verified my email address a second time and am now receiving email notifications.

**Comment by bess** [comment]
I have now re-verified all Tufts.edu email addresses, with the actual emails used by the system. I believe this closes this ticket.
