### ISSUE TITLE
Title should be singular

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#76]
**ACCEPTANCE**
- [ ] The `title` attribute does not allow multiple values (via importer, rails console, etc.).
- [ ] Metadata entry forms do not allow multiple titles to be entered (via user interface)

**Comment by little9** [comment]
There is a lot of code in Hyrax that assumes that title is an array. There will have to a lot of overrides 
to make sure that type errors don't creep in. I have a branch where I override the form so you can't create multiple titles in the interface.

I'd like to know if we really want to override Hyrax's CoreMetadata. I can understand why it would be important for the importer.

**Comment by no-reply** [comment]
In discussion at stand-up today, we agreed that we don't feel confident making `title` `multiple: false`, due to how baked into Hyrax the field is. Especially, there will be a lot of Hyrax level code that is untested in the local app but facing potential breakage.

The proposed alternative is a validator that ensures `title` has exactly one value. We think this would be easy to write, and allow us to restrict, rather than replace, Hyrax's current behavior.

**Comment by no-reply** [comment]
I've assigned @mark-dce and @mkorcy for comments on this. We'll hold off on writing the validator until monday.

**Comment by mkorcy** [comment]
@no-reply We discussed this when looking at adopting Curation concerns, and just agreed that this would be enforced by practice not code convention since it was counter to how CC/Hyrax wanted to handle title(s).  But on a self-deposit form there should be only one title field because it'd be confusing for a faculty and students to be able to enter multiple.
