### ISSUE TITLE
HANDLE: Store handle as fully resolvable URL

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#763]
**STORY**
As a repository administrator, I would like to continue storing handles in fully resolvable form, so that I don't have to update content in existing records in the production repository.

**ACCEPTANCE**
- [x] Newly generated handles are stored with the handle.net url prefix - i.e. when I register a new handle for `10427/8018`, I would like to store `http://hdl.handle.net/10427/8018`
- [x] Existing handles in the form `http://hdl.handle.net/10427/15565` remain unchanged by any background jobs
- [ ] If I enter any other kind of string in the `Permanent URL` (dc.identifier) field, it remains unmolested - i.e. If a users enters "This is not a handle" in the field, the system should leave it as is.

**Comment by no-reply** [comment]
@mark-dce I missed the last requirement on this. It snuck in on me because it seems unrelated to the ticket title, and isn't a requirement we had called out in the original implementation.

>  If I enter any other kind of string in the Permanent URL (dc.identifier) field, it remains unmolested - i.e. If a users enters "This is not a handle" in the field, the system should leave it as is.

Before I start work on this, can we confirm that we *do* need to rework this. I think the requirements would be that:

  - [ ] Non-handles in the `identifier` field are not changed when registering or updating handles.
  - [ ] Objects with *only* non-handles in the `identifier` field are treated as not having handles.

Currently, an item with "not a handle" in `identifier` is treated as having a handle across the board; this is probably the cause of https://app.honeybadger.io/projects/54127/faults/35581060.
