### ISSUE TITLE
Batch statuses

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#908]
We're noticing new batch statuses, such as "New" that we don't know how to interpret. We also don't know how to differentiate between "partially completed" and "in progress." Is there a controlled vocabulary for batch statuses and/or definitions of what they mean.

![statuses](https://user-images.githubusercontent.com/16196574/37044608-ecb20cfe-2131-11e8-8568-0d5e0ad3bb31.JPG)

**Comment by shanitajohn** [comment]
Job status "new" is specific XML import where there are no items in the batch.

**Comment by no-reply** [comment]
For most batches, there's a straight-forward workflow that goes like this:

  - `Queued` (the jobs for the batch are queued, but none are currently working)
  - `In Progress` (at least one job in the batch is working or completed)
  - `Completed` (all jobs in the batch have finished successfully)

Batch status can also time out, leading to `Unprioritized`.

Unlike in legacy MIRA, there is no `Error` status, since background jobs that error are re-enqueued safely to be rerun. Such jobs will go to http://epigaea.curationexperts.com/sidekiq/retries and, eventually http://epigaea.curationexperts.com/sidekiq/morgue.

----

For XML Import jobs, there are two special cases:

  - `New` (the batch exists, but no files have been uploaded)
  - `Partially Completed` (all queued jobs for the batch are completed, but more remain to be uploaded)

These relate to the ways that file uploads are handled. When a new XML Import batch is created, it has no jobs to queue until files are uploaded that can be processed. Such batches are `New` until a file is uploaded, at which point they will become `Queued`, etc...

If not all files are uploaded at once, a batch may enter a state where all queued jobs are completed, but the batch still has work to do; i.e. it is waiting for a user to upload more files. These batches are `Partially Completed`.

**Comment by no-reply** [comment]
You should normally see all XML Import batches enter the `New` state, but `Partially Completed` shouldn't pop up unless you have neglected to upload some files in your normal workflow.

**Comment by mark-dce** [comment]
Closing and @mkorcy will transfer relevant information to an internal document pool.

NOTE: Relevant constants are set in the batch presenter.
