### ISSUE TITLE
Sorting in Works appears to only sort the items on the page, not all items

### ISSUE THREAD

**Issue by sarimauro** [curationexperts/epigaea#911]
I know there are issues with sort, but I believe this one is outside them:

In Batch Statuses it is possible to (accurately) sort all batch numbers in the system, and it appears that other sort functions also act on the entirety of the batches in the system, though it does so inaccurately. 

In Works, sorting only appears to order the items which appear on the page. That is, if I am displaying 10 items per page and and try to sort by date, it only reorders the 10 items on that page. Ideally, it should function as it does from the Batch page and sort all items in the system for it to have any kind of usability.

**Comment by mark-dce** [comment]
It looks like this is happening because the views in question are only sorting in the browser.  The fix @little9 did for the batches does the sorting on the server side (so that the sort happens across the whole list of items instead of just the list being displayed).  We agree with @sarimauro that the current implementation in Hyrax isn't particularly useful, but any fix would need to happen to the Hyrax gem itself since far to much code would have to be overwritten locally to fix this just for Tufts.

**Comment by no-reply** [comment]
I've opened a Hyrax ticket for this at https://github.com/samvera/hyrax/issues/2858

**Comment by mark-dce** [comment]
Closing as this bug will be addressed in a future Hyrax release - samvera/hyrax#2858
